// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

//Auto generated by implement 'flutterfire configure' on terminal

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP83bzg83xmmM74eDo4e4nvV4MwgB__A0',
    appId: '1:243564777686:web:d8c58ecf3f655fa1833977',
    messagingSenderId: '243564777686',
    projectId: 'authenticationtesting-67e9e',
    authDomain: 'authenticationtesting-67e9e.firebaseapp.com',
    storageBucket: 'authenticationtesting-67e9e.firebasestorage.app',
    measurementId: 'G-96R1TDNX4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCErfAUsgzmMmxRrSg4zqbsgvEiu7X3Tf8',
    appId: '1:243564777686:android:97a2bfcc5cba3e30833977',
    messagingSenderId: '243564777686',
    projectId: 'authenticationtesting-67e9e',
    storageBucket: 'authenticationtesting-67e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2J-WjoqIom-nsQ7ep6nS7qHaCekPF-4',
    appId: '1:243564777686:ios:00a42e5b816083fd833977',
    messagingSenderId: '243564777686',
    projectId: 'authenticationtesting-67e9e',
    storageBucket: 'authenticationtesting-67e9e.firebasestorage.app',
    iosBundleId: 'com.example.digitalCertificateProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2J-WjoqIom-nsQ7ep6nS7qHaCekPF-4',
    appId: '1:243564777686:ios:00a42e5b816083fd833977',
    messagingSenderId: '243564777686',
    projectId: 'authenticationtesting-67e9e',
    storageBucket: 'authenticationtesting-67e9e.firebasestorage.app',
    iosBundleId: 'com.example.digitalCertificateProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP83bzg83xmmM74eDo4e4nvV4MwgB__A0',
    appId: '1:243564777686:web:92f1f4bd9db222da833977',
    messagingSenderId: '243564777686',
    projectId: 'authenticationtesting-67e9e',
    authDomain: 'authenticationtesting-67e9e.firebaseapp.com',
    storageBucket: 'authenticationtesting-67e9e.firebasestorage.app',
    measurementId: 'G-DRHNH5PRVD',
  );
}
